export * from './prisma-access-principal.repository';
export * from './prisma-credential.repository';
export * from './prisma-federated-account.repository';
export * from './prisma-iam-read-model.repository';
export * from './prisma-identity-provider.repository';
export * from './prisma-invitation.repository';
export * from './prisma-provisioned-access.repository';
export * from './prisma-user-account.repository';
export * from './prisma-user-session.repository';
