import type { Internship } from '../../domain/aggregates/internship.aggregate.js';
import type { InternshipDetailDto, InternshipListItemDto } from '../dto/internship.dto.js';

export const toInternshipListItemDto = (
  internship: Internship,
  cityName: string | null,
): InternshipListItemDto => ({
  id:                  internship.id,
  title:               internship.title,
  bannerImageUrl:      internship.bannerImageUrl,
  cityName,
  vacancies:           internship.vacancies,
  stipend:             internship.stipend,
  durationMonths:      internship.durationMonths,
  applicationDeadline: internship.applicationDeadline?.toISOString() ?? null,
  internshipType:      internship.internshipType,
  status:              internship.status,
});

export const toInternshipDetailDto = (
  internship: Internship,
  cityName: string | null,
): InternshipDetailDto => ({
  id:                          internship.id,
  tenantId:                    internship.tenantId,
  companyTenantId:             internship.companyTenantId,
  title:                       internship.title,
  bannerImageUrl:              internship.bannerImageUrl,
  vacancies:                   internship.vacancies,
  cityId:                      internship.cityId,
  cityName,
  stipend:                     internship.stipend,
  durationMonths:              internship.durationMonths,
  applicationDeadline:         internship.applicationDeadline?.toISOString() ?? null,
  internshipType:              internship.internshipType,
  status:                      internship.status,
  internshipDetail:            internship.internshipDetail,
  roleOverview:                internship.roleOverview,
  keyResponsibilities:         internship.keyResponsibilities,
  eligibilityRequirements:     internship.eligibilityRequirements,
  timelineWorkSchedule:        internship.timelineWorkSchedule,
  perksAndBenefits:            internship.perksAndBenefits,
  selectionProcess:            internship.selectionProcess,
  contactInformation:          internship.contactInformation,
  screeningQuestions:          internship.screeningQuestions,
  eligibilityCheck:            internship.eligibilityCheck,
  assessments:                 internship.assessments,
  interviewRubric:             internship.interviewRubric,
  offerLetterTemplateUrl:      internship.offerLetterTemplateUrl,
  termsConditionUrl:           internship.termsConditionUrl,
  offerLetterReleaseMethod:    internship.offerLetterReleaseMethod,
  functionalGroupId:           internship.functionalGroupId,
  preInternshipCommunication:  internship.preInternshipCommunication,
  preReadCourses:              internship.preReadCourses,
  preReadArticles:             internship.preReadArticles,
  batches:                     internship.batches,
  totalWeeks:                  internship.totalWeeks,
  weeklySchedule:              internship.weeklySchedule,
  midTermFeedbackDate:         internship.midTermFeedbackDate?.toISOString() ?? null,
  finalSubmissionDocuments:    internship.finalSubmissionDocuments,
  documentGuidelines:          internship.documentGuidelines,
  presentationRubricUrl:       internship.presentationRubricUrl,
  minPresentationScore:        internship.minPresentationScore,
  presentationWeightage:       internship.presentationWeightage,
  certificateTemplateUrl:      internship.certificateTemplateUrl,
  createdBy:                   internship.createdBy,
  createdOn:                   internship.createdOn.toISOString(),
  updatedOn:                   internship.updatedOn.toISOString(),
});
