name: Docker Image CI - api

on:
  push:
    tags:
      - 'api-*'

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login \
            -u lilcom \
            --password-stdin

      - name: Extract image tag
        run: |
          TAG=${GITHUB_REF_NAME#whizard-courses-}
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Build Docker image (courses)
        run: |
          docker build \
            -f services/courses/Dockerfile \
            -t lilcom/whizard-platform-api:${IMAGE_TAG} \
            .

      - name: Push Docker image
        run: |
          docker push lilcom/whizard-courses:${IMAGE_TAG}
